### ISSUE TITLE
Relocate findUser() from each class into UserRepo

### ISSUE THREAD

**Issue by hfaerber** [hfaerber/Refactor-tractor-Fit-lit#2]
Each class is using this method to isolate the data for the specific user in question.  **HOWEVER - in activity/sleep/hydration - this findUser() method is actually finding the activity/sleep/hydration stats for the specified user, not the user object.  Perhaps a Utility class is best for this?

We can move this into the User Repo class, run it in User Repo and pass its return value into the User class instantiation as a parameter.

That way the User class only ever has the data for the one single User it cares about.
Also, the findUser() method will only need run once rather than being run in so many methods like it currently is.

**Does the returnUserData(userID) method in UserRepo do the same thing as the findUser() method in each class?

**We may want to save this for last because making this change may mean we have to refactor how many methods pull data in all the classes.

**Comment by Dunn-Austen** [comment]
We resolved this by absorbing up the three findUser() methods spread across activity, hydration, and sleep into a single method within the Utility class. This single function returns an array of a specific user's data objects, whereas the returnUserData(userID) in the UserRepo returns a single object. For this reason, (for now) we've left the userRepo method untouched.

Consider this issue resolved.
