### ISSUE TITLE
Semantic HTML Naming

### ISSUE THREAD

**Issue by NaomiKC92** [hfaerber/Refactor-tractor-Fit-lit#29]
### Fix HTML tags to be more semantic and rename misused article tags

**Comment by AjeaSmith** [comment]
I'd like to work on this issue if its okay

**Comment by hfaerber** [comment]
> I'd like to work on this issue if its okay

Hi Ajeasmith -  thanks for checking!  We're students working on this project for a grade so we need to keep the work between us unfortunately.   Otherwise we'd love the help.  Have a great day!

**Comment by AjeaSmith** [comment]
Ok Cool, thanks for letting me know, have a good one! 😊

**Comment by hfaerber** [comment]
Changed the header area element from section to header.  
Changed all article tags to section tags.  
Renamed data-article class to data-subsection class.  
Removed all class names that were not being used anywhere.
Confirmed that all changes have been reflected in all files.

These changes have been committed and will be reflected in a future PR.
