### ISSUE TITLE
Rename SleepRepo method to longestSleeper (remove 's' bc not plural)

### ISSUE THREAD

**Issue by hfaerber** [hfaerber/Refactor-tractor-Fit-lit#31]
This method wasn't modified in your PR but looking at it - can we rename to reflect longest Sleeper by date?  It will only ever return one user ID.

_Originally posted by @hfaerber in https://github.com/hfaerber/Refactor-tractor-Fit-lit/pull/28_

**Comment by NaomiKC92** [comment]
Fixed all instances and verified all files compiled successfully
@hfaerber @Dunn-Austen
